version: "3.4"

services:
  redis:
    restart: always
    image: daocloud.io/library/redis:3.2.9
    container_name: redis_dev
    volumes: 
      - D:\dockerData\redis\:/var/lib/redis
    ports:
      - 6379:6379
    environment: 
      TZ: Asia/Shanghai
  mongodb:
    restart: always
    image: daocloud.io/library/mongo:3.5
    container_name: mongodb_dev
    volumes: 
      - D:\dockerData\mongodb\:/var/lib/mongodb
    ports: 
      - 27017:27017
    environment: 
      TZ: Asia/Shanghai
